In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
happy_2015 = "Resources/2015.csv"
happy_2016 = "Resources/2016.csv"
happy_2017 = "Resources/2017.csv"
happy_2018 = "Resources/2018.csv"
happy_2019 = "Resources/2019.csv"

happy_2015_df = pd.read_csv(happy_2015)
happy_2016_df = pd.read_csv(happy_2015)
happy_2017_df = pd.read_csv(happy_2015)
happy_2018_df = pd.read_csv(happy_2015)
happy_2019_df = pd.read_csv(happy_2015)

In [14]:
# JOIN THE DATA

#Create joins to merge file into single dataframe, with an added column for year

for row in happy_2015:
    happy_2015_df['Year'] = "2015"
    happy_2016_df['Year'] = "2016"
    happy_2017_df['Year'] = "2017"
    happy_2018_df['Year'] = "2018"
    happy_2019_df['Year'] = "2019"

# Merge two dataframes using an outer join
happy1516_df = pd.merge(happy_2015_df, happy_2016_df, how="outer")
happy151617_df = pd.merge(happy1516_df, happy_2017_df, how="outer")
happy15161718_df = pd.merge(happy151617_df, happy_2018_df, how="outer")
full_dataset_df = pd.merge(happy15161718_df, happy_2019_df, how="outer")

full_dataset_df

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042,2019
786,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328,2019
787,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858,2019
788,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302,2019
789,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726,2019

In [8]:
#CLEAN THE DATA: Aline, Susan

#Inspect columns to see if row counts match up
#Is object type pulling in as number? If not, change to numbers
#Run a groupby for country to check for typos
#Check for and handle NaN and null fields *as appropriate*

In [12]:
#CREATE DATAFRAMES: 

# DF Set 1: Meghan, Tom
#Happiness score, country name, GDP -- calculate correlation coefficient and pull into df
#Generosity, country name, GDP -- calculate correlation coefficient and pull into df

# DF Set 2: James, Aline
#Life expectancy, corruption, freedom
#life expectancy, happiness, GDP -- chaos ensues

In [10]:
#BINNING?

#Happiness rank, top 10?

In [ ]:
#Bar graph/stacked bar graph of happiness percentage change over time?